package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ketnoi.Conn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trantoai
 */
public class NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();
        this.loadTypeNV();
        this.loadBM();
        this.loadNV();
    }
    public void loadTypeNV()
    {
        //jComboBox_TypeNV.removeAllItems();
        Connection conn = Conn.conn();
        String sql = "SELECT TENLOAI FROM LOAINV";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet listType = ps.executeQuery();
            while(listType.next())
            {
                jComboBox_TypeNV.addItem(listType.getString("TENLOAI"));
            }
            listType.close();
            ps.close();
            conn.close();
        }
        catch(SQLException|NullPointerException e)
        {
           JOptionPane.showMessageDialog(this, "Tải dữ liệu thất bại, vui lòng kiểm tra kết nối");
           //jDialog_NV.setVisible(false);
        }
    }
    public void loadBM()
    {
        //jComboBox_TypeNV.removeAllItems();
        Connection conn = Conn.conn();
        String sql = "SELECT TENTBM FROM TOBOMON";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet listType = ps.executeQuery();
            while(listType.next())
            {
                jComboBox_Khoa.addItem(listType.getString("TENTBM"));
            }
            listType.close();
            ps.close();
            conn.close();
        }
        catch(SQLException|NullPointerException e)
        {
           JOptionPane.showMessageDialog(this, "Tải dữ liệu thất bại, vui lòng kiểm tra kết nối");
           //jDialog_NV.setVisible(false);
        }
    }
    public String getTBM_NV(String id){
        Connection conn = Conn.conn();
        String sql = "SELECT TENTBM FROM TOBOMON, NHANVIEN WHERE NHANVIEN.MATBM = TOBOMON.MATBM AND NHANVIEN.MANV = ?";
        String result = "";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
                result = rs.getString("TENTBM");
            
        }
        catch(SQLException|NullPointerException e)
        {
           result = "";
        }
        return result;
    }
    public void loadNV() {
        Vector v ;
        DefaultTableModel tableNV = (DefaultTableModel) jTable_NV.getModel();
        tableNV.setRowCount(0);
        Connection conn = Conn.conn();
        String sql = "SELECT * FROM V_NHANVIEN";
        try{
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet listNV = st.executeQuery();
            while(listNV.next())
            {
                v = new Vector();
                v.add(listNV.getString("MANV"));
                v.add(listNV.getString("HOTEN"));
                v.add(listNV.getString("EMAIL"));
                v.add(listNV.getString("DIACHI"));
                v.add(listNV.getString("SEX"));
                v.add(listNV.getString("TENPBK"));
                v.add(listNV.getString("LOAINV"));
                tableNV.addRow(v);
            }
            jTable_NV.setModel(tableNV);
                listNV.close();
                st.close();
                conn.close();
                //JOptionPane.showMessageDialog(this, "Tải dữ liệu thành công");
        }
        catch(SQLException|NullPointerException e)
        {
           JOptionPane.showMessageDialog(this, "Tải dữ liệu thất bại, vui lòng kiểm tra kết nối");
           //jDialog_NV.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_NVSex = new javax.swing.ButtonGroup();
        jLabel_NV = new javax.swing.JLabel();
        jPanel_Detail = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel_MaNV = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_Add = new javax.swing.JLabel();
        jTextField_Add = new javax.swing.JTextField();
        jLabel_Type = new javax.swing.JLabel();
        jComboBox_TypeNV = new javax.swing.JComboBox<>();
        jLabel_Khoa = new javax.swing.JLabel();
        jComboBox_Khoa = new javax.swing.JComboBox<>();
        jLabel_Sex = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_NV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_NV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NV.setText("DANH SÁCH CÁN BỘ GIẢNG VIÊN");

        jPanel_Detail.setLayout(new java.awt.GridLayout(4, 4));

        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name.setText("Họ tên");
        jPanel_Detail.add(jLabel_Name);
        jPanel_Detail.add(jTextField_Name);

        jLabel_MaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MaNV.setText("Mã nhân viên");
        jPanel_Detail.add(jLabel_MaNV);

        jTextField_Id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_IdMouseExited(evt);
            }
        });
        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });
        jPanel_Detail.add(jTextField_Id);

        jLabel_Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Email.setText("Email");
        jPanel_Detail.add(jLabel_Email);
        jPanel_Detail.add(jTextField_Email);

        jLabel_Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Add.setText("Địa chỉ");
        jPanel_Detail.add(jLabel_Add);
        jPanel_Detail.add(jTextField_Add);

        jLabel_Type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Type.setText("Loại nhân viên");
        jPanel_Detail.add(jLabel_Type);

        jComboBox_TypeNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TypeNVActionPerformed(evt);
            }
        });
        jPanel_Detail.add(jComboBox_TypeNV);

        jLabel_Khoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Khoa.setText("Tổ/Bộ môn");
        jPanel_Detail.add(jLabel_Khoa);

        jPanel_Detail.add(jComboBox_Khoa);

        jLabel_Sex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Sex.setText("Giới tính");
        jPanel_Detail.add(jLabel_Sex);

        buttonGroup_NVSex.add(jRadioButton_Male);
        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Nam");
        jPanel_Detail.add(jRadioButton_Male);

        buttonGroup_NVSex.add(jRadioButton_Female);
        jRadioButton_Female.setText("Nữ");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });
        jPanel_Detail.add(jRadioButton_Female);

        jButton1.setText("Thêm");
        jButton1.setToolTipText("");

        jButton2.setText("Xóa");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(107, 107, 107)
                .addComponent(jButton3)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTable_NV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ tên", "Email", "Địa chỉ", "Giới tính", "Khoa", "Loại NV"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_NV.setMaximumSize(new java.awt.Dimension(2147483647, 164));
        jTable_NV.setMinimumSize(new java.awt.Dimension(105, 164));
        jTable_NV.setPreferredSize(new java.awt.Dimension(525, 160));
        jTable_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_NV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(927, 927, 927))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_IdMouseExited
        // TODO add your handling code here:
        //  JOptionPane.showMessageDialog(this, "Tải dữ liệu thất bại, vui lòng kiểm tra kết nối");
    }//GEN-LAST:event_jTextField_IdMouseExited

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jComboBox_TypeNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TypeNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TypeNVActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    private void jTable_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NVMouseClicked
        // TODO add your handling code here:
        int i = jTable_NV.getSelectedRow();
        DefaultTableModel tableNV = (DefaultTableModel) jTable_NV.getModel();
        jTextField_Id.setText((String) tableNV.getValueAt(i, 0));
        jTextField_Name.setText((String) tableNV.getValueAt(i, 1));
        jTextField_Email.setText((String) tableNV.getValueAt(i, 2));
        jTextField_Add.setText((String) tableNV.getValueAt(i, 3));
        if(tableNV.getValueAt(i, 4).toString().toLowerCase().equals("nam"))

        jRadioButton_Male.setSelected(true);
        else
        jRadioButton_Female.setSelected(true);

        jComboBox_TypeNV.setSelectedItem(tableNV.getValueAt(i, 6).toString());
        jComboBox_Khoa.setSelectedItem(this.getTBM_NV(tableNV.getValueAt(i, 0).toString()));

    }//GEN-LAST:event_jTable_NVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_NVSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Khoa;
    private javax.swing.JComboBox<String> jComboBox_TypeNV;
    private javax.swing.JLabel jLabel_Add;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Khoa;
    private javax.swing.JLabel jLabel_MaNV;
    private javax.swing.JLabel jLabel_NV;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Sex;
    private javax.swing.JLabel jLabel_Type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Detail;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_NV;
    private javax.swing.JTextField jTextField_Add;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
